apiVersion: apps/v1
kind: Deployment
metadata:
  name: zodiac-deployment-green
  labels:
    app: zodiac-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zodiac-app
      role: green
  template:
    metadata:
      labels:
        app: zodiac-app
        role: green
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: zodiac-rest-app
          image: ravishbhupesh/zodiac-app:2.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
