apiVersion: v1
kind: Service
metadata:
  name: zodiac-svc
spec:
  type: NodePort
  selector:
    app: zodiac-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111