apiVersion: v1
kind: Service
metadata:
  name: zodiac-svc-lb-pub
  labels:
    app: zodiac-app
    role: green
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: zodiac-app
    role: green
  ports:
    - port: 80
      targetPort: 8080