apiVersion: v1
kind: Service
metadata:
  name: zodiac-svc-lb-green-test
  labels:
    app: zodiac-app
    role: green-test
    env: test
spec:
  type: LoadBalancer
  selector:
    app: zodiac-app
    role: green
  ports:
    - port: 8001
      targetPort: 8080