apiVersion: v1
kind: Service
metadata:
  name: zodiac-svc-lb-blue-test
  labels:
    app: zodiac-app
    role: blue-test
    env: test
spec:
  type: LoadBalancer
  selector:
    app: zodiac-app
    role: blue
  ports:
    - port: 8000
      targetPort: 8080